services:
  - type: web
    name: ppjo-pdl-app
    runtime: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    startCommand: bash /var/www/html/docker/start-web.sh
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
      - key: APP_URL
        value: https://ppjo-pdl-management-system.onrender.com
      - key: APP_KEY
        value: base64:aq3HV7grgQwWN3qEPyawwoDAH5zJhfgYEezqIVhg2yU=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: database
      - key: RUN_DB_SEED_ON_BOOT
        value: "false"
      - key: MONGODB_MIRROR_ENABLED
        value: "false"
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        sync: false
      - key: MONGODB_MIRROR_COLLECTION
        value: pdls_mirror

  - type: worker
    name: ppjo-pdl-worker
    runtime: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile.worker
    startCommand: bash /var/www/html/docker/start-worker.sh
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
      - key: APP_URL
        value: https://ppjo-pdl-management-system.onrender.com
      - key: APP_KEY
        value: base64:aq3HV7grgQwWN3qEPyawwoDAH5zJhfgYEezqIVhg2yU=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: database
      - key: MONGODB_MIRROR_ENABLED
        value: "false"
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        sync: false
      - key: MONGODB_MIRROR_COLLECTION
        value: pdls_mirror
